export default [
    {
      "id": "9d2b1c238f-013d-45cd-bfb8-aded8bb182c7",
      "title": "Tshirt",
      "description": "Lightweight, breathable tees to rep the squad in style.",
      "price": "99.99",
      "image": "/products/TSHIRTS_WHITE.webp",
      "category": "TSHIRTS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "eb57ac00-49f0-402b-9bf1-de1f6139974c",
      "title": "Trouser",
      "description": "Comfortable joggers made for gaming and everyday wear.",
      "price": "99.99",
      "image": "/products/TROUSERS_WHITE.webp",
      "category": "TROUSERS",
      "quantity": "1",
      "color": "white",
      "size": "md",

    },
    {
      "id": "9f178e394a-b69a-4ab8-bf0f-6d00699829c9",
      "title": "Hoodie",
      "description": "Stay warm and stylish with our ultra-comfy gaming hoodie.",
      "price": "99.99",
      "image": "/products/HOODIES_WHITE.webp",
      "category": "HOODIES",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "851900fc-388b-4378-9633-e744c4b422a9",
      "title": "SweatShirt",
      "description": "Soft, cozy, and perfect for gaming or casual wear.",
      "price": "99.99",
      "image": "/products/SWEATSHIRTS_WHITE.webp",
      "category": "SWEATSHIRTS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "mjdiof84edlef-rdifu84dn98-943ufnndk",
      "title": "Keychain",
      "description": "Carry a piece of the community wherever you go.",
      "price": "99.99",
      "image": "/products/KEYCHAINS_WHITE.webp",
      "category": "KEYCHAINS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "khu3y673edb32723-49823eg387-904ffrbg",
      "title": "Shorts",
      "description": "Lightweight and comfy shorts for relaxed gaming sessions.",
      "price": "99.99",
      "image": "/products/SHORTS_WHITE.webp",
      "category": "SHORTS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "mkm94382yw8edbq26ww-39823wedwb-38eywd",
      "title": "Notebook",
      "description": "Jot down notes, ideas, or game strategies on the go.",
      "price": "99.99",
      "image": "/products/NOTEBOOKS_WHITE.webp",
      "category": "NOTEBOOKS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "0932eu-39387edjcn-39hsd93e465hdgedfr",
      "title": "Cap",
      "description": "A classic cap to top off your gamer look.",
      "price": "99.99",
      "image": "/products/CAPS_WHITE.webp",
      "category": "CAPS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "9382e0dn837-4093ewndwrf-3we09ud3u8e",
      "title": "Mobile Cover",
      "description": "Sleek, durable cover to protect your phone in style.",
      "price": "99.99",
      "image": "/products/MOBILECOVERS_WHITE.webp",
      "category": "MOBILECOVERS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "0we6525e4wdv-2w7etd7edncx-83ywedn",
      "title": "Mousepad",
      "description": "Smooth, high-precision surface for peak gaming performance.",
      "price": "99.99",
      "image": "/products/MOUSEPADS_WHITE.webp",
      "category": "MOUSEPADS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
    {
      "id": "938e0nwd83-3we982wmdo-92uqwsdg",
      "title": "Mug",
      "description": "Fuel up with a gamer-themed mug set for every mood.",
      "price": "99.99",
      "image": "/products/MUGS_WHITE.webp",
      "category": "MUGS",
      "quantity": "1",
      "color": "white",
      "size": "md",
    },
];